stats = [
{	enemyId: EnemyType.Melee,
	enemyName: ObjBasicShadow,
	hitPoints: 5,
	image_xscale: 1.5,
	image_yscale: 1.5,
	image_angle: 0,
	speed: 3.5,
	minDistance: 0,
},
{	enemyId: EnemyType.Ranged,
	enemyName: ObjRangedShadow,
	hitPoints: 3,
	image_xscale: 1.75,
	image_yscale: 1.75,
	image_angle: 0,
	speed: 2.5,
	minDistance: 350,
}
]